django-level-five/users/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('users_app/', include('users_app.urls')),
    path('admin/', admin.site.urls),
]

django-level-five/users/users_app/urls.py
from django.urls import path
from users_app import views

# TEMPLATE TAGGING
app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name="register")

]

django-level-five/users/users_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

django-level-five/users/users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from users_app.models import UserProfileInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

django-level-five/users/users_app/views.py
from django.shortcuts import render
from users_app.forms import UserForm, UserProfileInfoForm


# Create your views here.

def index(request):
    return render(request, 'users_app/index.html')


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }

    return render(request, 'users_app/registration.html', context)

django-level-five/users/templates/users_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>

    <nav>
        <div class="container nav-wrapper">
          <a href="{% url 'index' %}" class="brand-logo">Logo</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href="{% url 'users_app:register' %}">Register</a></li>
          </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

django-level-five/users/templates/users_app/index.html
{% extends 'users_app/base.html' %}

{% block content %}
    <div class="container">
        <h4>Djago Level Five</h4>
    </div>
{% endblock %}

django-level-five/users/templates/users_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django-level-five/users/templates/users_app/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django-level-five/users/templates/users_app/registration.html
{% extends 'users_app/base.html' %}

{% block content %}
    <div class="container">
        {% if registered %}
            <h4>Thank you for registering!</h4>
        {% else %}
            <h4>Register Here!</h4>
        <form action=""  enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p}}
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
        {% endif %}
    </div>
{% endblock %}