django-level-four/temp_demo/temp_app/urls.py
from django.urls import path
from . import views


# Template Tagging
app_name = "temp_app"

urlpatterns = [
    path('other/', views.other, name="other"),
    path('relative/', views.relative, name="relative")
]

django-level-four/temp_demo/temp_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from temp_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('temp_app/', include('temp_app.urls')),
    path('admin/', admin.site.urls),
]

django-level-four/temp_demo/temp_app/models.py
from django.db import models

# Create your models here.

django-level-four/temp_demo/temp_app/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    context = {
        'text': 'hello World',
        'number': 100
    }
    return render(request, 'temp_app/index.html', context)


def other(request):
    return render(request, 'temp_app/other.html')


def relative(request):
    return render(request, 'temp_app/relative.html')

django-level-four/temp_demo/templates/temp_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <style>
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
          }
    </style>
</head>
<body>
    <nav>
        <div class="container nav-wrapper">
          <a href="{% url 'index' %}" class="brand-logo">Logo</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href="{% url 'temp_app:other' %}">Other</a></li>
          </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
            <!-- Anything outside this will be inherited if we extend -->
        {% endblock %}
    </div>
    <footer class="page-footer" style="padding-top:0px;">
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 center" href="#!">More Links</a>
            </div>
          </div>
    </footer>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

django-level-four/temp_demo/templates/temp_app/index.html
{% extends 'temp_app/base.html' %}

{% block content %}
    <h2>Welcome to Index</h2>
    <h3>This is an example of Template Inheritance!</h3>
    <h4>{{ text | cut:'hello' }}</h4>
    <h6>{{ number | add:"45"}}</h6>
{% endblock %}

django-level-four/temp_demo/templates/temp_app/other.html
{% extends 'temp_app/base.html' %}

{% block content %}
    <h2>Welcome to Other</h2>
    <h3>This is an example of Template Inheritance!</h3>
{% endblock %}

django-level-four/temp_demo/templates/temp_app/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Relative Html File</h2>
    <a href="{% url 'temp_app:other' %}">Go to other Html Page</a>
    <a href="{% url 'admin:index' %}">Go to Admin Page</a>
    <a href="{% url 'index' %}">Go to index</a>
</body>
</html>